name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
    tags: ["*"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build Package
        run: |
          mvn clean package -Dquarkus.package.type=uber-jar -DskipTests
          jpackage --input target/ \
            --dest ./build \
            --name devtools \
            --main-jar devtools-1.0.0-SNAPSHOT-runner.jar \
            --type app-image \
            --java-options '--enable-preview -Dfile.encoding=UTF8'
      - name: Upload Binary
        uses: adrianolaselva/action-build-and-upload-binary@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          OWNER: adrianolaselva
          REPOSITORY: devtools
          TAG: ${{ github.ref }}