name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
    tags: ["*"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
#    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build Package
        run: |
          make build-package
      - name: Upload Binary
        uses: adrianolaselva/action-build-and-upload-binary@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          OWNER: ${{ github.repository_owner }}
          REPOSITORY: ${{ github.repository }}
          TAG: ${{ github.ref }}
          SHA: ${{ github.sha }}